config/routes.rb
Todo::Application.routes.draw do
  resources :items do
    collection { post :sort }
  end
  resources :lists
  resources :categories

  devise_for :users

  root :to => 'lists#index'

end

app/models/list.rb
class List < ActiveRecord::Base
  belongs_to :category
  has_many :items, dependent: :destroy, order: :position

  accepts_nested_attributes_for :items, reject_if: proc { |i| i['name'].blank? }, allow_destroy: true

  attr_accessible :category_id, :name, :items_attributes

  delegate :name, to: :category, prefix: true

  validates :category, :name, presence: true
  validates :name, length: { within: 3..25 }
end

app/controllers/lists_controller.rb
class ListsController < ApplicationController
  before_filter :authenticate_user!

  # GET /lists
  # GET /lists.json
  def index
    @lists = List.includes(:category, :items).order('categories.name, lists.name').all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @lists }
    end
  end

  # GET /lists/1
  # GET /lists/1.json
  def show
    @list = List.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/new
  # GET /lists/new.json
  def new
    @list = List.new
    2.times { @list.items.build }

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @list }
    end
  end

  # GET /lists/1/edit
  def edit
    @list = List.find(params[:id])
    if @list.items.empty?
      2.times { @list.items.build }
    end
  end

  # POST /lists
  # POST /lists.json
  def create
    @list = List.new(params[:list])
    if @list.items.empty?
      2.times { @list.items.build }
    end

    respond_to do |format|
      if @list.save
        format.html { redirect_to @list, notice: 'List was successfully created.' }
        format.json { render json: @list, status: :created, location: @list }
      else
        format.html { render action: "new" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /lists/1
  # PUT /lists/1.json
  def update
    @list = List.find(params[:id])

    respond_to do |format|
      if @list.update_attributes(params[:list])
        format.html { redirect_to @list, notice: 'List was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @list.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /lists/1
  # DELETE /lists/1.json
  def destroy
    @list = List.find(params[:id])
    @list.destroy

    respond_to do |format|
      format.html { redirect_to lists_url }
      format.json { head :no_content }
    end
  end
end

app/views/lists/_form.html.slim
= semantic_form_for @list do |f|
  = f.inputs "List Info", id: 'info' do
    = f.input :category_id, as: :select, collection: current_user.categories
    = link_to 'Add new category', new_category_path
    = f.input :name
  = f.inputs "Items", id: 'items' do
    = f.fields_for :items do |builder|
      = render 'item_fields', f: builder
    = link_to_add_fields "Add item", f, :items

  = f.actions

app/views/lists/_item_fields.html.slim
div
  - if f.object.errors.any?
    p.notice= "At least one item is required"
  = f.semantic_errors
  = f.label :name, 'Item '
  = f.text_field :name
  = f.hidden_field :_destroy
  = link_to 'remove', '#', class: 'remove_fields'

app/views/lists/edit.html.erb
<h1>Editing list</h1>

<%= render 'form' %>

<%= link_to 'Show', @list %> |
<%= link_to 'Back', lists_path %>

app/views/lists/index.html.slim
h3 To Do Lists
- @lists.each do |list|
  p
    = link_to list.category_name, category_path(list.category)
    = ' - '
    = link_to list.name, list_path(list)
- if @lists.empty?
  p You have no lists!
p= link_to 'Add a list', new_list_path

app/views/lists/new.html.slim
h1 Add A List

= render 'form'

= link_to 'View Lists', lists_path

app/views/lists/show.html.slim
p#notice= notice

p
  strong Category
p= link_to @list.category_name, category_path(@list.category)

p
  strong Name
p= @list.name

p
  strong Items
ul#item_list[data-update-url="#{sort_items_url}"]
  - @list.items.each do |item|
    - if item.complete?
      - partial = 'items/complete'
    - else
      - partial = 'items/incomplete'
    = render partial: partial, locals: { item: item }

p= link_to 'Edit List', edit_list_path(@list)