config/routes.rb
Todo::Application.routes.draw do
  resources :items do
    collection { post :sort }
  end
  resources :lists
  resources :categories

  devise_for :users

  root :to => 'lists#index'

end

app/models/category.rb
class Category < ActiveRecord::Base
  belongs_to :user

  has_many :lists, dependent: :destroy
  has_many :items, through: :lists

  attr_accessible :name
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :authenticate_user!

  # GET /categories
  # GET /categories.json
  def index
    @categories = Category.where(user_id: current_user.id).all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @categories }
    end
  end

  # GET /categories/1
  # GET /categories/1.json
  def show
    @category = Category.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/new
  # GET /categories/new.json
  def new
    @category = current_user.categories.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @category }
    end
  end

  # GET /categories/1/edit
  def edit
    @category = Category.find(params[:id])
  end

  # POST /categories
  # POST /categories.json
  def create
    @category = Category.new(params[:category])
    @category.user_id = current_user.id

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: 'Category was successfully created.' }
        format.json { render json: @category, status: :created, location: @category }
      else
        format.html { render action: "new" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /categories/1
  # PUT /categories/1.json
  def update
    @category = Category.find(params[:id])

    respond_to do |format|
      if @category.update_attributes(params[:category])
        format.html { redirect_to @category, notice: 'Category was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1
  # DELETE /categories/1.json
  def destroy
    @category = Category.find(params[:id])
    @category.destroy

    respond_to do |format|
      format.html { redirect_to categories_url }
      format.json { head :no_content }
    end
  end
end

app/views/categories/_form.html.slim
= semantic_form_for @category do |f|
  = f.input :name
  = f.actions

app/views/categories/edit.html.slim
h1 Edit Category

= render 'form'

= link_to 'All Categories', categories_path

app/views/categories/index.html.slim
h1 Categories

- @categories.each do |category|
  p
    = link_to category.name, category_path(category)
    = ' ('
    = link_to 'edit', edit_category_path(category)
    = ')'

= link_to 'All Lists', lists_path
br
= link_to 'Add Category', new_category_path

app/views/categories/new.html.slim
h1 Add Category

= render 'form'

= link_to 'All Categories', categories_path

app/views/categories/show.html.slim
p#notice= notice

p
  strong Name: &nbsp;
  = @category.name

p
  strong Lists:

- @category.lists.each do |list|
  p= link_to list.name, list_path(list)

= link_to 'Edit', edit_category_path(@category)
= ' | '
= link_to 'All Categories', categories_path